### ISSUE TITLE
配列にする必要はないです

### ISSUE THREAD

**Issue by amapyon** [manayamano/pg_ex21#1]
https://github.com/manayamano/pg_ex21/blob/7b54f7b301a8585cc1f383a11de826ec277736dd/src/pg_ex21/Pg_ex21.java#L20

仕様にある、
「最大行数は未定義。数百万行を越すことが予定されている。」
を考慮すると、10000でも足りない可能性が高いです。

**Comment by manayamano** [comment]
確認いただきありがとうございます。
配列を利用していたところを、ArrayListに修正しました。
このようにすると問題ないでしょうか？

**Comment by manayamano** [comment]
そもそもuserの変数は１つで問題ないですね。。
修正しました。

**Comment by amapyon** [comment]
気付いていただけれ嬉しいです。
ソースコードもきれいになって、みやすくなりました。
